# Generated by Django 4.2.6 on 2023-11-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='restore_folder_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
