# Generated by Django 4.2.6 on 2023-11-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbuser',
            name='trash_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
